default_platform(:ios)

api_key = app_store_connect_api_key(
  key_id: "92AVKRC5U8",
  issuer_id: "69a6de84-0da9-47e3-e053-5b8c7c11a4d1",
  key_filepath: "fastlane/AuthKey.p8"
)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number(
      xcodeproj: "SwiftDiscourseHub.xcodeproj"
    )
    build_app(
      scheme: "SwiftDiscourseHub",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end

platform :mac do
  desc "Build and upload to TestFlight for macOS"
  lane :beta do
    increment_build_number(
      xcodeproj: "SwiftDiscourseHub.xcodeproj"
    )
    build_mac_app(
      scheme: "SwiftDiscourseHub",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )
    pkg_path = lane_context[SharedValues::PKG_OUTPUT_PATH]
    UI.message("PKG path: #{pkg_path}")
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      pkg: pkg_path
    )
  end
end
